package logradouro

type TipoLograd string

var (
	ACAMP    TipoLograd = "ACAMP"    // ACAMPAMENTO
	AC       TipoLograd = "AC"       // ACESSO
	AD       TipoLograd = "AD"       // ADRO
	AER      TipoLograd = "AER"      // AEROPORTO
	AL       TipoLograd = "AL"       // ALAMEDA
	AT       TipoLograd = "AT"       // ALTO
	A        TipoLograd = "A"        // AREA
	ART      TipoLograd = "ART"      // ARTERIA
	ATL      TipoLograd = "ATL"      // ATALHO
	AV       TipoLograd = "AV"       // AVENIDA
	BX       TipoLograd = "BX"       // BAIXA
	BLO      TipoLograd = "BLO"      // BALAO
	BAL      TipoLograd = "BAL"      // BALNEARIO
	BC       TipoLograd = "BC"       // BECO
	BELV     TipoLograd = "BELV"     // BELVEDERE
	BL       TipoLograd = "BL"       // BLOCO
	BSQ      TipoLograd = "BSQ"      // BOSQUE
	BVD      TipoLograd = "BVD"      // BOULEVARD
	BCO      TipoLograd = "BCO"      // BURACO
	C        TipoLograd = "C"        // CAIS
	CXP      TipoLograd = "CXP"      // CAIXA POSTAL
	CALC     TipoLograd = "CALC"     // CALCADA
	CAM      TipoLograd = "CAM"      // CAMINHO
	CPO      TipoLograd = "CPO"      // CAMPO
	CAN      TipoLograd = "CAN"      // CANAL
	CH       TipoLograd = "CH"       // CHACARA
	CHAP     TipoLograd = "CHAP"     // CHAPADAO
	CIRC     TipoLograd = "CIRC"     // CIRCULAR
	COL      TipoLograd = "COL"      // COLONIA
	CMP_VR   TipoLograd = "CMP-VR"   // COMPLEXO VIARIO
	COND     TipoLograd = "COND"     // CONDOMINIO
	CJ       TipoLograd = "CJ"       // CONJUNTO
	COR      TipoLograd = "COR"      // CORREDOR
	CRG      TipoLograd = "CRG"      // CORREGO
	DSC      TipoLograd = "DSC"      // DESCIDA
	DSV      TipoLograd = "DSV"      // DESVIO
	DT       TipoLograd = "DT"       // DISTRITO
	EVD      TipoLograd = "EVD"      // ELEVADA
	ENT_PART TipoLograd = "ENT-PART" // ENTRADA PARTICULAR
	EQ       TipoLograd = "EQ"       // ENTRE QUADRAS
	ESC      TipoLograd = "ESC"      // ESCADA
	ESP      TipoLograd = "ESP"      // ESPLANADA
	ETC      TipoLograd = "ETC"      // ESTACAO
	ESTC     TipoLograd = "ESTC"     // ESTACIONAMENTO
	ETD      TipoLograd = "ETD"      // ESTADIO
	ETN      TipoLograd = "ETN"      // ESTANCIA
	EST      TipoLograd = "EST"      // ESTRADA
	FAV      TipoLograd = "FAV"      // FAVELA
	FAZ      TipoLograd = "FAZ"      // FAZENDA
	FRA      TipoLograd = "FRA"      // FEIRA
	FER      TipoLograd = "FER"      // FERROVIA
	FNT      TipoLograd = "FNT"      // FONTE
	FTE      TipoLograd = "FTE"      // FORTE
	GAL      TipoLograd = "GAL"      // GALERIA
	GJA      TipoLograd = "GJA"      // GRANJA
	HAB      TipoLograd = "HAB"      // HABITACIONAL
	IA       TipoLograd = "IA"       // ILHA
	JD       TipoLograd = "JD"       // JARDIM
	JDE      TipoLograd = "JDE"      // JARDINETE
	LD       TipoLograd = "LD"       // LADEIRA
	LG       TipoLograd = "LG"       // LAGO
	LGA      TipoLograd = "LGA"      // LAGOA
	LRG      TipoLograd = "LRG"      // LARGO
	LOT      TipoLograd = "LOT"      // LOTEAMENTO
	MNA      TipoLograd = "MNA"      // MARINA
	MOD      TipoLograd = "MOD"      // MODULO
	MTE      TipoLograd = "MTE"      // MONTE
	MRO      TipoLograd = "MRO"      // MORRO
	NUC      TipoLograd = "NUC"      // NUCLEO
	PDA      TipoLograd = "PDA"      // PARADA
	PDO      TipoLograd = "PDO"      // PARADOURO
	PAR      TipoLograd = "PAR"      // PARALELA
	PRQ      TipoLograd = "PRQ"      // PARQUE
	PSG      TipoLograd = "PSG"      // PASSAGEM
	PSG_SUB  TipoLograd = "PSG-SUB"  // PASSAGEM SUBTERRANEA
	PSA      TipoLograd = "PSA"      // PASSARELA
	PAS      TipoLograd = "PAS"      // PASSEIO
	PAT      TipoLograd = "PAT"      // PATIO
	PNT      TipoLograd = "PNT"      // PONTA
	PTE      TipoLograd = "PTE"      // PONTE
	PTO      TipoLograd = "PTO"      // PORTO
	PC       TipoLograd = "PC"       // PRACA
	PC_ESP   TipoLograd = "PC-ESP"   // PRACA DE ESPORTES
	PR       TipoLograd = "PR"       // PRAIA
	PRL      TipoLograd = "PRL"      // PROLONGAMENTO
	Q        TipoLograd = "Q"        // QUADRA
	QTA      TipoLograd = "QTA"      // QUINTA
	QTAS     TipoLograd = "QTAS"     // QUINTAS
	RAM      TipoLograd = "RAM"      // RAMAL
	RMP      TipoLograd = "RMP"      // RAMPA
	REC      TipoLograd = "REC"      // RECANTO
	RES      TipoLograd = "RES"      // RESIDENCIAL
	RET      TipoLograd = "RET"      // RETA
	RER      TipoLograd = "RER"      // RETIRO
	RTN      TipoLograd = "RTN"      // RETORNO
	ROD_AN   TipoLograd = "ROD-AN"   // RODO ANEL
	ROD      TipoLograd = "ROD"      // RODOVIA
	RTT      TipoLograd = "RTT"      // ROTATORIA
	ROT      TipoLograd = "ROT"      // ROTULA
	R        TipoLograd = "R"        // RUA
	R_PED    TipoLograd = "R-PED"    // RUA DE PEDESTRE
	SRV      TipoLograd = "SRV"      // SERVIDAO
	ST       TipoLograd = "ST"       // SETOR
	SIT      TipoLograd = "SIT"      // SITIO
	SUB      TipoLograd = "SUB"      // SUBIDA
	TEL      TipoLograd = "TEL"      // TELEFONE
	TER      TipoLograd = "TER"      // TERMINAL
	TV       TipoLograd = "TV"       // TRAVESSA
	TV_PART  TipoLograd = "TV-PART"  // TRAVESSA PARTICULAR
	TR       TipoLograd = "TR"       // TRECHO
	TRV      TipoLograd = "TRV"      // TREVO
	TCH      TipoLograd = "TCH"      // TRINCHEIRA
	TUN      TipoLograd = "TUN"      // TUNEL
	UNID     TipoLograd = "UNID"     // UNIDADE
	VAL      TipoLograd = "VAL"      // VALA
	VLE      TipoLograd = "VLE"      // VALE
	VRTE     TipoLograd = "VRTE"     // VARIANTE
	VER      TipoLograd = "VER"      // VEREDA
	V        TipoLograd = "V"        // VIA
	V_AC     TipoLograd = "V-AC"     // VIA DE ACESSO
	V_PED    TipoLograd = "V-PED"    // VIA DE PEDESTRE
	VD       TipoLograd = "VD"       // VIADUTO
	V_EVD    TipoLograd = "V-EVD"    // VIA ELEVADO
	V_EXP    TipoLograd = "V-EXP"    // VIA EXPRESSA
	VLA      TipoLograd = "VLA"      // VIELA
	VL       TipoLograd = "VL"       // VILA
	ZIG_ZAG  TipoLograd = "ZIG-ZAG"  // ZIGUE-ZAGUE
)
