package cod_categoria

type CodCategoria string

var (
	A_IMPORTACAO                 CodCategoria = "1000005" //  A: IMPORTACAO(CONTRAT. ADM.)
	A_OBSERVACAO                 CodCategoria = "5"       //  A: Observação
	C_ATA_REGISTRADA             CodCategoria = "107"     //  C: ATA REGISTRADA
	C_ATA_REGISTRADA_SITE        CodCategoria = "115"     //  C: ATA REGISTRADA - SITE
	C_ATAS                       CodCategoria = "17"      //  C: ATAS
	C_ATAS_AGES                  CodCategoria = "13"      //  C: ATAS AGE'S
	C_ATAS_AGOS                  CodCategoria = "14"      //  C: ATAS AGO'S
	C_ATAS_CONSELHO              CodCategoria = "117"     //  C: ATAS CONSELHO
	C_AUDITORIA                  CodCategoria = "140"     //  C: AUDITORIA
	C_AUTORIZACAO                CodCategoria = "15"      //  C: AUTORIZAÇÃO
	C_AVISOS_E_CIRCULARES        CodCategoria = "139"     //  C: AVISOS E CIRCULARES
	C_BALANCETE_DIGITAL          CodCategoria = "104"     //  C: BALANCETE DIGITAL
	C_BALANCETES                 CodCategoria = "118"     //  C: BALANCETES
	C_BOLETIM_INFORMATIVO        CodCategoria = "97"      //  C: BOLETIM INFORMATIVO
	C_CAPTACAO_DE_CONDOMINIOS    CodCategoria = "94"      //  C: CAPTAÇÃO DE CONDOMÍNIOS
	C_CERTIDAO_NEGATIVA          CodCategoria = "91"      //  C: CERTIDÃO NEGATIVA
	C_CERTIFICACAO_DIGITAL       CodCategoria = "148"     //  C: CERTIFICAÇÃO DIGITAL
	C_CERTIFICADO_DT_DR          CodCategoria = "179"     //  C: CERTIFICADO DT DR
	C_CERTIFICADO_LIMPEZA_CAIXAS CodCategoria = "178"     //  C: CERTIFICADO LIMPEZA DAS CAIXAS DE ÁGUA 2023
	C_CERTIFICADOS_MANUTENCOES   CodCategoria = "149"     //  C: CERTIFICADOS MANUTENÇÕES PERIÓDICAS
	C_CIRCULAR                   CodCategoria = "16"      //  C: CIRCULAR
	C_CONTRATO_ASSINADO          CodCategoria = "181"     //  C: contrato assinado
	C_CONTRATO_GESTAO_ICR        CodCategoria = "83"      //  C: CONTRATO GESTÃO ICR
	C_CONTRATO_ICR               CodCategoria = "12"      //  C: CONTRATO ICR
	C_CONTRATOS                  CodCategoria = "9"       //  C: CONTRATOS
	C_CONTRATOS_ENCERRADOS       CodCategoria = "116"     //  C: CONTRATOS ENCERRADOS
	C_CONTRATO_SINDICO_ICR       CodCategoria = "92"      //  C: CONTRATO SINDICO ICR
	C_CONVENCAO                  CodCategoria = "7"       //  C: CONVENCAO
	C_CONVOCACAO                 CodCategoria = "67"      //  C: CONVOCACAO
	C_CONVOCACAO_2               CodCategoria = "20"      //  C: CONVOCAÇÃO
	C_CONVOCACAO_AGE             CodCategoria = "18"      //  C: CONVOCAÇÃO AGE
	C_CORRESPONDENCIAS           CodCategoria = "19"      //  C: CORRESPONDENCIAS
	C_DOCUMENTOS_DIVERSOS_SITE   CodCategoria = "102"     //  C: DOCUMENTOS DIVERSOS - SITE
	C_EMAIL                      CodCategoria = "199"     //  C: E-MAIL
	C_ENCERRAMENTO_SALDO         CodCategoria = "72"      //  C: ENCERRAMENTO SALDO
	C_IMPORTACAO_CONDOM          CodCategoria = "1000000" //  C: IMPORTACAO(CONDOM)
	C_LAUDO                      CodCategoria = "81"      //  C: LAUDO
	C_LAUDO_MARQUISE             CodCategoria = "180"     //  C: LAUDO MARQUISE INICIAL 15/06/21
	C_MATRICULA_MAE              CodCategoria = "200"     //  C: MATRICULA MÃE
	C_MINUTA_CONVENCAO           CodCategoria = "110"     //  C: MINUTA DA CONVENÇÃO
	C_NOTIFICACOES_RESCISOES     CodCategoria = "80"      //  C: NOTIFICAÇÕES/ RESCISÕES DE CONTRATO
	C_OBSERVACAO                 CodCategoria = "1"       //  C: Observação
	C_ORCAMENTOS                 CodCategoria = "103"     //  C: ORÇAMENTOS
	C_OUTROS                     CodCategoria = "73"      //  C: OUTROS
	C_PAGAMENTOS_AUTORIZADOS     CodCategoria = "195"     //  C: PAGAMENTOS - PESSOAS AUTORIZADAS
	C_PARA_EXCLUIR               CodCategoria = "138"     //  C: PARA EXCLUIR
	C_PARECER_TECNICO            CodCategoria = "150"     //  C: PARECER TÉCNICO
	C_PLANTAS                    CodCategoria = "108"     //  C: PLANTAS
	C_PORTE_DISCRIMINADO         CodCategoria = "96"      //  C: PORTE DISCRIMINADO
	C_PREVISAO_ORCAMENTARIA      CodCategoria = "105"     //  C: PREVISÃO ORÇAMENTÁRIA
	C_PROCURACAO_ICR             CodCategoria = "10"      //  C: PROCURAÇÃO ICR
	C_PROTOCOLO                  CodCategoria = "119"     //  C: PROTOCOLO
	C_REGIMENTO_INTERNO          CodCategoria = "8"       //  C: REGIMENTO INTERNO
	C_REGULARIZACAO_IMOVEIS      CodCategoria = "89"      //  C: REGULARIZAÇÃO DE IMOVEIS
	C_RELATORIO_JURIDICO         CodCategoria = "93"      //  C: RELATÓRIO JURÍDICO
	C_SEGURO_FOGO                CodCategoria = "11"      //  C: SEGURO FOGO
	C_SOLICITACAO_CONDOMINIO     CodCategoria = "106"     //  C: SOLICITAÇÃO DE CONDOMÍNIO
	C_TESTE                      CodCategoria = "196"     //  C: TESTE
	E_ACORDO                     CodCategoria = "202"     //  E: ACORDO
	E_ACORDO_ADV                 CodCategoria = "189"     //  E: ACORDO ADV
	E_ALTERACAO_CADASTRAL        CodCategoria = "201"     //  E: Alteração cadastral
	E_COBRANCA                   CodCategoria = "68"      //  E: COBRANÇA
	E_NOTIFICACAO                CodCategoria = "75"      //  E: NOTIFICAÇÃO
	E_OBSERVACAO                 CodCategoria = "2"       //  E: Observação
	F_AUTORIZACAO                CodCategoria = "77"      //  F: AUTORIZAÇAO
	F_AUTORIZACAO_2              CodCategoria = "76"      //  F: AUTORIZAÇÃO
	F_CNPJ                       CodCategoria = "133"     //  F: CNPJ
	F_DADOS_BANCARIOS            CodCategoria = "132"     //  F: DADOS BANCARIOS
	F_ORIENTACAO_IMPOSTO         CodCategoria = "129"     //  F: ORIENTAÇÃO SOBRE IMPOSTO
	I_BENFEITORIAS               CodCategoria = "192"     //  I: benfeitorias imóvel
	I_CONVOCACAO                 CodCategoria = "130"     //  I: CONVOCAÇÃO
	I_DMAE                       CodCategoria = "128"     //  I: DMAE
	I_DOCUMENTOS_LOCATARIO       CodCategoria = "141"     //  I: DOCUMENTOS LOCATÁRIO
	I_DOCUMENTOS_PROPRIETARIO    CodCategoria = "142"     //  I: DOCUMENTOS PROPRIETÁRIO
	I_EMAIL                      CodCategoria = "146"     //  I: E-MAIL
	I_ENCARGOS                   CodCategoria = "87"      //  I: ENCARGOS
	I_IMAGENS_PROPRIETARIO       CodCategoria = "197"     //  I: Imagens prop.
	I_IMPORTACAO                 CodCategoria = "1000001" //  I: IMPORTACAO(IMOVEL)
	I_IPTU                       CodCategoria = "151"     //  I: IPTU
	I_MATRICULA                  CodCategoria = "100"     //  I: MATRICULA
	I_MELHORIAS                  CodCategoria = "198"     //  I: MELHORIAS NO IMÓVEL
	I_NOTIFICACAO                CodCategoria = "95"      //  I: NOTIFICAÇÃO
	I_OBSERVACAO                 CodCategoria = "3"       //  I: Observação
	I_PROCURACAO                 CodCategoria = "143"     //  I: PROCURAÇÃO
	I_PROTOCOLO                  CodCategoria = "120"     //  I: PROTOCOLO
	I_RETIRADA_MOVEIS            CodCategoria = "191"     //  I: RETIRADA DE MÓVEIS DO IMÓVEL
	I_TROCA_LOCADOR              CodCategoria = "187"     //  I: TROCA DE LOCADOR
	I_VISTORIA_CONTRATO          CodCategoria = "156"     //  I: VISTORIA/CONTRATO
	I_VISTORIA_DEVOLUS           CodCategoria = "175"     //  I: VISTORIA DEVOLUS
	L_ACORDO                     CodCategoria = "147"     //  L: ACORDO
	L_ADITAMENTO                 CodCategoria = "136"     //  L: aditamento
	L_ADITIVO                    CodCategoria = "126"     //  L: ADITIVO
	L_ADITIVO_REAJUSTE           CodCategoria = "78"      //  L: ADITIVO REAJUSTE
	L_APOLICE                    CodCategoria = "172"     //  L: APÓLICE
	L_CANCELAMENTO_APOLICE       CodCategoria = "171"     //  L: CANCELAMENTO DE APÓLICE
	L_COMPROVANTES               CodCategoria = "79"      //  L: COMPROVANTES
	L_CONTRATO                   CodCategoria = "122"     //  L: CONTRATO
	L_DESCONTO_ALUGUEL           CodCategoria = "158"     //  L: DESCONTO DE ALUGUEL
	L_EMAIL                      CodCategoria = "194"     //  L: EMAIL
	L_ENDOSSO_PORTO              CodCategoria = "173"     //  L: ENDOSSO PORTO SEGURO
	L_ENDOSSO_POTTENCIAL         CodCategoria = "174"     //  L: ENDOSSO POTTENCIAL
	L_FATURA_GAS                 CodCategoria = "159"     //  L: FATURA DE GÁS
	L_FIADOR_EXONERADO           CodCategoria = "86"      //  L: FIADOR/EXONERADO
	L_FICHA_CADASTRAL            CodCategoria = "144"     //  L: FICHA CADASTRAL
	L_IMPORTACAO                 CodCategoria = "1000003" //  L: IMPORTACAO(CONTRAT. LOC.)
	L_INDENIZACAO                CodCategoria = "167"     //  L: INDENIZAÇÃO
	L_INSTALACOES_SERVICOS       CodCategoria = "161"     //  L: INSTALAÇÕES E SERVIÇOS
	L_LAUDO_VISTORIA             CodCategoria = "127"     //  L: LAUDO VISTORIA
	L_LIMITE_GARANTIA            CodCategoria = "176"     //  L: LIMITE DE GARANTIA ESGOTADO
	L_NOTA_FISCAL                CodCategoria = "160"     //  L: NOTA FISCAL
	L_NOTIFICACAO                CodCategoria = "121"     //  L: NOTIFICAÇÃO
	L_OBSERVACAO                 CodCategoria = "4"       //  L: Observação
	L_OCORRENCIA                 CodCategoria = "190"     //  L: OCORRÊNCIA
	L_ORDEM_SERVICO              CodCategoria = "162"     //  L: ORDEM DE SERVIÇO
	L_PROCURACAO                 CodCategoria = "131"     //  L: PROCURAÇÃO
	L_PROTOCOLO                  CodCategoria = "124"     //  L: PROTOCOLO
	L_QUITACOES                  CodCategoria = "170"     //  L: QUITAÇÕES
	L_RECIBO_CHAVES              CodCategoria = "164"     //  L: RECIBO DE ENTREGA DE CHAVES
	L_RENOVACAO                  CodCategoria = "185"     //  L: RENOVAÇÃO
	L_SEGURO_FOGO                CodCategoria = "163"     //  L: SEGURO FOGO
	L_SINISTRO                   CodCategoria = "166"     //  L: SINISTRO
	L_TERMO_ACORDO               CodCategoria = "125"     //  L: TERMO ACORDO
	L_TERMO_ACORDO_2             CodCategoria = "135"     //  L: TERMO DE ACORDO
	L_TERMO_ACORDO_COMP_6_7      CodCategoria = "137"     //  L: TERMO DE ACORDO COMP 6 E 7
	L_TERMO_ACORDO_COMP_7        CodCategoria = "134"     //  L: TERMO DE ACORDO COMP 7
	L_VISTORIA                   CodCategoria = "123"     //  L: VISTORIA
	M_AUTORIZACAO_LOCACAO        CodCategoria = "85"      //  M: AUTORIZAÇÃO DE LOCAÇÃO
	M_BOLETIM_CADASTRO_TECNICO   CodCategoria = "74"      //  M: BOLETIM E CADASTRO TECNICO
	M_CONDOMINIO                 CodCategoria = "70"      //  M: CONDOMINIO
	M_FOTOS                      CodCategoria = "88"      //  M: FOTOS
	M_NEGOCIACAO                 CodCategoria = "84"      //  M: NEGOCIAÇÃO
	N_IPTU                       CodCategoria = "71"      //  N: IPTU
	N_NOTAS_RECIBOS_PAGOS        CodCategoria = "82"      //  N: NOTAS E RECIBOS PAGOS
	N_SOLICITACAO_DEPOSITO       CodCategoria = "69"      //  N: SOLICITAÇÃO DEPOSITO
	O_ADITIVO                    CodCategoria = "188"     //  O: ADITIVO
	O_CORRESPONDENCIAS           CodCategoria = "145"     //  O: CORRESPONDÊNCIAS
	O_DOCUMENTOS                 CodCategoria = "184"     //  O: DOCUMENTOS
	O_IMPORTACAO                 CodCategoria = "1000002" //  O: IMPORTACAO(PROP.)
	O_RG_PROP                    CodCategoria = "90"      //  O: RG PROP
	P_FOTO                       CodCategoria = "109"     //  P: FOTO
	P_FOTOS_INTERESSADO          CodCategoria = "66"      //  P: FOTOS INTERESSADO
	T_ADITIVO                    CodCategoria = "157"     //  T: ADITIVO
	T_ADVERTENCIA                CodCategoria = "193"     //  T: ADVERTÊNCIA
	T_AGUA_LUZ                   CodCategoria = "155"     //  T: AGUA/LUZ
	T_APOLICE                    CodCategoria = "168"     //  T: APÓLICE
	T_COMPROVANTE                CodCategoria = "182"     //  T: COMPROVANTE
	T_CONECTE_SE                 CodCategoria = "101"     //  T: Conecte-se
	T_DENUNCIA_VAZIA             CodCategoria = "154"     //  T: DENÚNCIA VAZIA
	T_DOCUMENTOS                 CodCategoria = "183"     //  T: DOCUMENTOS
	T_EMAIL                      CodCategoria = "152"     //  T: E-MAIL
	T_FATURA                     CodCategoria = "186"     //  T: FATURA
	T_GERAL                      CodCategoria = "99"      //  T: Geral
	T_INFO_PAGAMENTO_EXTRATO     CodCategoria = "111"     //  T: Informações sobre doc de pagamento e extratos
	T_IPTU                       CodCategoria = "153"     //  T: IPTU
	T_MANUTENCAO                 CodCategoria = "114"     //  T: Manutenção de ambientes e equipamentos
	T_OUTROS                     CodCategoria = "113"     //  T: Outros
	T_PLANILHA_REPAROS           CodCategoria = "177"     //  T: PLANILHA DE REPAROS
	T_VAZIO                      CodCategoria = "98"      //  T:
	T_RECIBO                     CodCategoria = "165"     //  T: RECIBO
	T_RECLAMACOES                CodCategoria = "112"     //  T: Reclamações sobre infrações a Convenção e Regulamento Interno
	T_RELATORIO_CONTA_CORRENTE   CodCategoria = "169"     //  T: RELATÓRIO DE CONTA CORRENTE
)
